FROM php:7.4-apache

RUN a2enmod rewrite

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

COPY . /var/www/html
WORKDIR /var/www/html

RUN chmod +x bin/console

# composer :
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY composer.json ./
COPY composer.lock ./
RUN composer install --no-scripts --no-autoloader
COPY . ./
RUN composer dump-autoload --optimize && \
	composer run-script post-install-cmd

EXPOSE 80/tcp
EXPOSE 443/tcp